In [3]:
import pandas as pd
import os

In [5]:
data_dir = '../glue_data/'

In [32]:
import csv
def _read_tsv(input_file):
    """Reads a tab separated value file."""
    with open(input_file, "r", encoding="utf-8-sig") as f:
        return list(csv.reader(f, delimiter="\t"))

In [15]:
mnli = pd.read_csv(os.path.join(data_dir,'MNLI/dev_matched.tsv'), delimiter='\t')
mnli_mm = pd.read_csv(os.path.join(data_dir,'MNLI/dev_mismatched.tsv'), delimiter='\t')

In [16]:
mnli.groupby('gold_label').count()/len(mnli)

,index,promptID,pairID,genre,sentence1_binary_parse,sentence2_binary_parse,sentence1_parse,sentence2_parse,sentence1,sentence2,label1,label2,label3,label4,label5
gold_label,,,,,,,,,,,,,,,
contradiction,0.327260,0.327260,0.327260,0.327260,0.327260,0.327260,0.327260,0.327260,0.327260,0.327260,0.327260,0.327260,0.327260,0.327260,0.327260
entailment,0.354231,0.354231,0.354231,0.354231,0.354231,0.354231,0.354231,0.354231,0.354231,0.354231,0.354231,0.354231,0.354231,0.354231,0.354231
neutral,0.318509,0.318509,0.318509,0.318509,0.318509,0.318509,0.318509,0.318509,0.318509,0.318509,0.318509,0.318509,0.318509,0.318509,0.318509

In [17]:
mnli_mm.groupby('gold_label').count()/len(mnli_mm)

,index,promptID,pairID,genre,sentence1_binary_parse,sentence2_binary_parse,sentence1_parse,sentence2_parse,sentence1,sentence2,label1,label2,label3,label4,label5
gold_label,,,,,,,,,,,,,,,
contradiction,0.329536,0.329536,0.329536,0.329536,0.329536,0.329536,0.329536,0.329536,0.329536,0.329536,0.329536,0.329536,0.329536,0.329536,0.329536
entailment,0.352217,0.352217,0.352217,0.352217,0.352217,0.352217,0.352217,0.352217,0.352217,0.352217,0.352217,0.352217,0.352217,0.352217,0.352217
neutral,0.318247,0.318247,0.318247,0.318247,0.318247,0.318247,0.318247,0.318247,0.318247,0.318247,0.318247,0.318247,0.318247,0.318247,0.318247

In [52]:
rte = pd.read_csv(os.path.join(data_dir, 'RTE/dev.tsv' ), delimiter='\t')
rte

,index,sentence1,sentence2,label
0,0,"Dana Reeve, the widow of the actor Christopher...",Christopher Reeve had an accident.,not_entailment
1,1,"Yet, we now are discovering that antibiotics a...",Bacteria is winning the war against antibiotics.,entailment
2,2,Cairo is now home to some 15 million people - ...,15 million tonnes of rubbish are produced dail...,not_entailment
3,3,"The Amish community in Pennsylvania, which num...",Pennsylvania has the biggest Amish community i...,not_entailment
4,4,Security forces were on high alert after an el...,Security forces were on high alert after a cam...,entailment
5,5,"In 1979, the leaders signed the Egypt-Israel p...",The Israel-Egypt Peace Agreement was signed in...,entailment
6,6,"singer and actress Britney Spears, 24, has fil...",Spears is to divorce from Kevin Federline.,entailment
7,7,Following the successful bid to bring the 2010...,Wales to host 2010 Ryder Cup.,entailment
8,8,Steve Jobs was attacked by Sculley and other A...,Steve Jobs worked for Apple.,entailment
9,9,"Traditionally, the Brahui of the Raisani tribe...",The Raisani tribe resides in Pakistan.,entailment
10,10,The international humanitarian aid organizatio...,Doctors Without Borders is an international ai...,entailment
11,11,"In a bowl, whisk together the eggs and sugar u...","In a bowl, whisk together the egg, sugar and v...",not_entailment
12,12,"In Nigeria, by far the most populous country i...",2.7 percent of the people infected with HIV li...,not_entailment
13,13,A jury is slated to decide for the first time ...,"Jack Kevorkian is the real name of ""Dr. Death"".",entailment
14,14,Take consumer products giant Procter and Gambl...,Procter and Gamble spends $1.8 billion for Res...,entailment
15,15,Deceased U.S. soldiers and their effects were ...,The U.S. military evacuated U.S. citizens.,not_entailment
16,16,Mice given a substance found in red wine lived...,Mice fed with red wine lived longer despite a ...,not_entailment
17,17,Charles de Gaulle died in 1970 at the age of e...,Charles de Gaulle died in 1970.,entailment
18,18,Teenage sensation Wayne Rooney powered England...,France participates in Euro 2004.,entailment
19,19,"Fujimori charged that on January 26, 1995, Ecu...",President Fujimori was re-elected in 1995.,not_entailment
20,20,"Hepburn's platinum, diamond and sapphire brooc...",Hepburn's diamond and sapphire brooch fetched ...,entailment
21,21,Huckaby voluntarily submitted herself to quest...,Huckaby is accused of killing Sandra Cantu.,entailment
22,22,"CAMDEN, N.J. (Reuters) — Three Muslim brothers...",Eljvir Duka comes from Albania.,entailment
23,23,A number of the items that he auctioned off ov...,The Osbournes is the name of a reality show st...,entailment
24,24,"According to reports, a man protesting the G20...",Sky News offices are close to the Bank of Engl...,not_entailment
25,25,"The San Diego Padres ace, Jake Peavy, was hurt...",The San Diego Padres won the game against the ...,not_entailment
26,26,"Despite CNOOC's all-cash bid, Unocal said its ...",Unocal said it would evaluate the CNOOC offer.,not_entailment
27,27,U.S. forces have been engaged in intense fight...,Fallujah and Baqubah are Iraqi cities.,entailment
28,28,But Huawei says that expansion has not been ea...,Chinese engineers working on long-term project...,not_entailment
29,29,According to Becky Gibbons of New York State P...,A daily commuter flight crashed in Buffalo.,not_entailment
...,...,...,...,...
247,247,With South Carolina being Jesse Jackson's home...,Jesse Jackson was born in South Carolina.,entailment
248,248,"NASA estimated, Monday, that it will cost $104...",The new space vehicle design uses shuttle rock...,not_entailment
249,249,Most commercial logwood is grown in Honduras.,Plants are grown in water or in substances oth...,not_entailment
250,250,Arlene Blum is a legendary trailblazer by any ...,A woman succeeds in climbing Everest solo.,not_entailment
251,251,"Gabriel Garcia Marquez is the author of ""One H...",Gabriel Garcia Marquez is a novelist and writer.,entailment
252,252,The investigation involving Mr Lopez and three...,Seven other GM executives left with Lopez.,not_entailment
253,253,High dietary intake of potassium from fruits a...,Dietary intake of potassium prevents osteoporo...,entailment
254,254,"Monica Meadows, a 22-year-old model from Atlan...","Monica Meadows, 23, was shot in shoulder while...",not_entailment
255,255,Phish disbands after a final concert in Vermon...,Rock band Phish holds final concert in Vermont.,entailment
256,256,Plans are being drawn up to build a £3.3m work...,Charles Darwin took a voyage on a ship named H...,entailment
257,257,The most sought after piece and the most expen...,The highest-selling item was a bronze bust mad...,entailment
258,258,Hadley said Jordan was chosen as the site of t...,Bush will meet al-Maliki in Hadley.,not_entailment
259,259,A senior coalition official in Iraq said the b...,A body has been found by U. S. military police.,entailment
260,260,Oqueli was to fly to Nicaragua to join an inte...,An electoral campaign is being held in Nicaragua.,entailment
261,261,JERUSALEM (AP) -- In a spiritual climax to his...,Pope John Paul II was born in Poland.,not_entailment
262,262,"Aeschylus was born in 525 BC, and spent his yo...",The Persians was written by Aeschylus.,entailment
263,263,The Croatian intent is even more problematic b...,There is a territorial waters dispute.,entailment
264,264,Hurricane Katrina petroleum-supply outlook imp...,60 million barrels of oil and gasoline will be...,not_entailment
265,265,Thursday's assassination of Ms. Bhutto has plu...,Musharraf has ordered rioters to take firm act...,not_entailment
266,266,"In 1865, John Wilkes Booth, the assassin of Pr...",John Wilkes Booth killed President Abraham Lin...,entailment
267,267,The letter received by Syracuse TV station New...,Jiverly Won was a police chief.,not_entailment
268,268,"As a result, peptic ulcer disease has been tra...",Antibiotics are used against peptic ulcer.,entailment
269,269,"In the history of art, prehistoric art is all ...",Prehistoric art discovered in South Africa.,not_entailment
270,270,"The capital of Slovenia is Ljubljana, with 270...","Slovenia has 270,000 inhabitants.",not_entailment
271,271,A new report indicates that women's participat...,Women are poorly represented in parliament.,not_entailment
272,272,Swansea striker Lee Trundle has negotiated a l...,Lee Trundle is in business with the League One...,entailment
273,273,A light blue 1975 Ford Escort GL once owned by...,A Houston multimillionaire buys the Pope's For...,entailment
274,274,"On October 1 2001, EU and other countries intr...","In 2001, the EU introduced a passport for pets.",entailment
275,275,Kozlowski and the company's former chief finan...,"Kozlowski was sentenced, Monday, to serve up t...",entailment
276,276,"Danny Kennedy, Greenpeace campaigns director, ...",Greenpeace director said that peace is terrorism.,not_entailment

In [20]:
rte.groupby('label').count()/len(rte)

                   index  sentence1  sentence2
label
entailment      0.527076   0.527076   0.527076
not_entailment  0.472924   0.472924   0.472924

In [22]:
wnli = pd.read_csv (os.path.join(data_dir, 'WNLI/dev.tsv'), delimiter='\t')
# wnli

In [23]:
wnli.groupby('label').count()/len(wnli)

         index  sentence1  sentence2
label
0      0.56338    0.56338    0.56338
1      0.43662    0.43662    0.43662

In [44]:
qnli = pd.read_csv (os.path.join(data_dir, 'QNLI/dev.tsv'), delimiter="\t")
qnli

,index,question,sentence,label
0,0,What came into force after the new constitutio...,"As of that day, the new constitution heralding...",entailment
1,1,What is the first major city in the stream of ...,The most important tributaries in this area ar...,not_entailment
2,2,What is the minimum required if you want to te...,In most provinces a second Bachelor's Degree s...,not_entailment
3,3,How was Temüjin kept imprisoned by the Tayichi...,The Tayichi'ud enslaved Temüjin (reportedly wi...,entailment
4,4,"What did Herr Gott, dich loben wir become know...","He paraphrased the Te Deum as ""Herr Gott, dich...",not_entailment
5,5,What year did the the case go before the supre...,"For example, Joseph Haas was arrested for alle...",not_entailment
6,6,What does UMC stand for?,Founded in 1968 by the union of the Methodist ...,not_entailment
7,7,What is the name of the professional skateboar...,Southern California is also important to the w...,not_entailment
8,8,Where did Temüjin hide during his escape from ...,Temüjin's reputation also became widespread af...,not_entailment
9,9,What are the most active parts of ctenophora?,These branch through the mesoglea to the most ...,entailment
10,10,Who decides the fate of protesters most of the...,"Brownlee argues, ""Bringing in deterrence at th...",not_entailment
11,11,What act sets forth the functions of the Scott...,"The Scotland Act 1998, which was passed by the...",entailment
12,12,What is the name for a response of the immune ...,Hypersensitivity is an immune response that da...,entailment
13,13,When did the Warsaw Uprising begin?,the Polish government-in-exile in London gave ...,not_entailment
14,14,The Tower District is centered around which hi...,The theater was built in 1939 and is at Olive ...,not_entailment
15,15,What is the English translation of Het Scheur?,The largest and southern main branch begins as...,entailment
16,16,What is one of the largest music schools in Eu...,Other institutions for higher education includ...,entailment
17,17,What percentage of farmland grows wheat?,"More than 50% of this area is sown for wheat, ...",entailment
18,18,What did he light at his laboratories to demon...,He lit electric lamps wirelessly at both locat...,entailment
19,19,Where did the Exposition take place?,This World's Fair devoted a building to electr...,not_entailment
20,20,What is a ligand on the cell surface that is u...,"In addition, helper T cell activation causes a...",entailment
21,21,When did Warsaw become the center of the Congr...,Warsaw remained the capital of the Polish–Lith...,not_entailment
22,22,Which country does the Rhine encounter it's ma...,It is here that the Rhine encounters some more...,not_entailment
23,23,"If two thirds of the Rhine flows through Waal,...",The other third of the water flows through the...,entailment
24,24,What paved the way for the Augsburg Confession?,"Despite the disagreements on the Eucharist, th...",entailment
25,25,What signer of the Articles of Confederation w...,Paul Revere was descended from Huguenot refuge...,entailment
26,26,What language did Tesla study while in school?,Tesla was the fourth of five children.,not_entailment
27,27,In what year did the university first see a dr...,"In the early 1950s, student applications decli...",entailment
28,28,What causes the symptoms of inflammation?,"The symptoms of inflammation are redness, swel...",entailment
29,29,In which case did the Court state that Austria...,In Commission v Austria the Court held that Au...,entailment
...,...,...,...,...
5241,5433,Persistent unemployment has what effect on lon...,Policies aiming at controlling unemployment an...,not_entailment
5242,5434,What is the translation of the old north branc...,"From Wijk bij Duurstede, the old north branch ...",entailment
5243,5435,How many refugees emigrated to the Dutch Repub...,"In 1705, Amsterdam and the area of West Frisia...",not_entailment
5244,5436,What was intended for the site of the former b...,The 1950s and early 1960s saw little in the wa...,not_entailment
5245,5437,Who translated and printed Luther's 95 These?,"Within two weeks, copies of the theses had spr...",not_entailment
5246,5438,$500 Million was supplied for the Capital City...,"To finance the purchase, Capital Cities borrow...",not_entailment
5247,5439,What was Iqbal studying in England and Germany?,While studying law and philosophy in England a...,entailment
5248,5440,What was the Rhine considered to invaders in W...,"In World War II, it was recognised that the Rh...",entailment
5249,5441,Who provided a definition of linear bounded au...,Earlier papers studying problems solvable by T...,entailment
5250,5442,How high are Victoria's alpine regions?,"Victoria contains many topographically, geolog...",entailment
5251,5443,What did John Dobson describe Newcastle as?,The city has an extensive neoclassical centre ...,not_entailment
5252,5444,What makes the Wells Fargo Center stand out?,The tallest building in Downtown Jacksonville'...,not_entailment
5253,5445,This person proposed explanations for the orig...,"Some modern scholars, such as Fielding H. Garr...",not_entailment
5254,5446,What other former halftime show performer join...,"On January 7, 2016, Pepsi confirmed to the Ass...",not_entailment
5255,5447,What lands were reserved for natives?,Included in its provisions was the reservation...,entailment
5256,5448,How much percentage of Victoria's land is take...,This comprises more than 60% of the state's to...,entailment
5257,5449,When do chloroplasts produce defense signals?,"After detecting stress in a cell, which might ...",entailment
5258,5450,When did the Rhine become borders with Francia?,"By the 6th century, the Rhine was within the b...",entailment
5259,5451,Who develped the theory of relativity?,"By the early 20th century, Einstein developed ...",entailment
5260,5452,In which Middle Eastern country is Genghis Kha...,"In Turkey, Genghis Khan is looked on as a grea...",entailment
5261,5453,What percentage of Warsaw's population was Pro...,"According to the 1901 census, out of 711,988 i...",entailment
5262,5454,Who previously held the record for being the o...,"The past record was held by John Elway, who le...",entailment
5263,5455,What criticism in NY times article that impact...,"Since 2008, undergraduate students have been r...",not_entailment
5264,5456,What process down the line does rubisco's flaw...,This has the end result of ATP energy being wa...,not_entailment
5265,5457,Who did Denver beat in the 2015 AFC Championsh...,The Broncos finished the regular season with a...,entailment
5266,5458,How many people lived in Warsaw in 1939?,Unfortunately this belief still lives on in Po...,not_entailment
5267,5459,One of FIS' agenda items was to force women to...,Taking advantage of economic failure and unpop...,entailment
5268,5460,Dendritic cells are named that because they re...,Dendritic cells serve as a link between the bo...,not_entailment
5269,5461,When did it retract to a inland formation?,"However, the rainforest still managed to thriv...",not_entailment
5270,5462,Who discovered this and where did they come from?,The development of this fertile soil allowed a...,not_entailment

In [41]:
qnli.groupby('label').count()/len(qnli)

                   index  question  sentence
label
entailment      0.494024  0.494024  0.494024
not_entailment  0.505976  0.505976  0.505976

In [51]:
print(len (_read_tsv('../adversarial_glue_data/QNLI/shuffle_question/dev.tsv')), len(pd.read_csv('../adversarial_glue_data/QNLI/shuffle_sent/dev.tsv', delimiter='\t')))

5272 5271